# Override file for local development
version: '3.8'

services:
  frontend-dev:
    environment:
      - VITE_BACKEND_URI=localhost
      - VITE_BACKEND_PORT=8000
    volumes:
      - .:/app:cached
      - /app/node_modules
    stdin_open: true
    tty: true

  cypress:
    environment:
      - CYPRESS_baseUrl=http://localhost:5173
    volumes:
      - .:/app:cached
      - cypress_cache:/root/.cache/Cypress